### ISSUE TITLE
Change keyboard color?

### ISSUE THREAD

**Issue by Matt319** [mnvoh/DigitInputView#4]
How can I change the color of the keyboard from light to dark? Thanks.

**Comment by mnvoh** [comment]
There needs to be a public property for setting `UITextInputTraits`, in this case:

```swift
textfield.keyboardAppearance = UIKeyboardAppearance.dark
```

You can apply these changes and create a new pull request, otherwise I'll do it in the next couple of days when I have time, maybe even tomorrow. 

cheers

**Comment by mnvoh** [comment]
You can use the latest version `1.1.1` now and use the `keyboardAppearance` property.
